/**
 * Analytics constants + per-page Google Ads conversion routing.
 *
 * SINGLE SOURCE OF TRUTH for the Google tag IDs and the per-LP conversion
 * catalog. The site loads gtag.js in app/layout.tsx using GA4_ID and GADS_ID;
 * conversion events are routed to the correct Google Ads action based on the
 * current pathname via getConversionForPath().
 *
 * Two conversion-firing styles are supported, because Google Ads' 2026 UI
 * generates two different snippet patterns depending on which path you take
 * when creating the conversion action:
 *
 *   1. send_to (legacy) — snippet looks like:
 *        gtag('event', 'conversion', {
 *          'send_to': 'AW-994138570/<LABEL>',
 *          'value': 1500.0,
 *          'currency': 'USD'
 *        });
 *      Generated by Google Ads when you pick "Install the tag yourself".
 *      Use kind: 'send_to' + `label`.
 *
 *   2. event-name (new) — snippet looks like:
 *        gtag('event', '<EVENT_NAME>', { ... });
 *      Generated by Google Ads when you pick "Create with code" inside the
 *      goal flow. The conversion fires when the Google tag sees this event
 *      name. Value is set in the Google Ads UI but can be overridden here.
 *      Use kind: 'event' + `eventName`.
 *
 * Per-LP conversion routing (May 2026):
 *   /team-building-monterey  → phone $1,500 (send_to), form $1,500 (event), no booking
 *   (other LPs)              → not yet configured — add as conversions are
 *                              created in Google Ads
 *
 * To add a new LP's conversions:
 *   1. Create the conversion action(s) in Google Ads
 *   2. Note whether Google gave you a `send_to` label or a custom event name
 *   3. Add an entry to CONVERSIONS below with the matching pathPrefix
 *
 * The trackConversion() helper is the ONE place that fires the Google Ads
 * conversion event. Call it from outbound-link click handlers and form
 * submit handlers. It uses event_callback to defer navigation until the
 * tag actually fires (with a 1-2s failsafe).
 */

export const GA4_ID = process.env.NEXT_PUBLIC_GA4_ID ?? 'G-W2QRVH1SY8';
export const GADS_ID = process.env.NEXT_PUBLIC_GADS_ID ?? 'AW-994138570';
export const GADS_ID_SECONDARY = process.env.NEXT_PUBLIC_GADS_ID_SECONDARY ?? 'AW-18137623591';

export type ConversionType = 'phone' | 'form' | 'booking';

type ConversionConfig =
  | {
      /** Legacy style — fires `gtag('event', 'conversion', { send_to, ... })`. */
      kind: 'send_to';
      /** The label string after the slash in `<AW-account>/<label>`. */
      label: string;
      /** Which Google Ads account owns this conversion. Defaults to GADS_ID. */
      accountId?: string;
      /** Default monetary value for this conversion. */
      value: number;
      /** Currency for value. Defaults to USD. */
      currency?: string;
    }
  | {
      /** New style — fires `gtag('event', '<eventName>', { ... })`. */
      kind: 'event';
      /** Custom event name registered in Google Ads as the conversion trigger. */
      eventName: string;
      /** Optional value override; defaults to value configured in Google Ads UI. */
      value?: number;
      /** Currency for value. Defaults to USD. */
      currency?: string;
    };

/**
 * Per-page conversion catalog. First match wins; iterate in order and pick
 * the first entry whose pathPrefix matches `pathname.startsWith(prefix)`.
 * Use an empty-string pathPrefix as the site-wide fallback (last entry only).
 *
 * Per-account scoping (May 2026):
 *   AW-994138570 tracks the groups sales phone (831-648-7236) on
 *     /team-building-monterey only.
 *   AW-18137623591 tracks the reservations phone (831-372-1807) on the
 *     5 reservations LPs + homepage.
 *   Each phone click fires exactly one named conversion in exactly one
 *     account — no dual-fire.
 */
const CONVERSIONS: ReadonlyArray<{
  pathPrefix: string;
  conversions: Partial<Record<ConversionType, ConversionConfig>>;
}> = [
  {
    // Groups / team-building LP — high-value phone + form, no FareHarbor.
    // Consolidated to AW-18137623591 alongside the reservations conversions
    // so the entire ABTS funnel reports in one account. AW-994138570 group
    // phone/form conversions in the old account should be archived.
    pathPrefix: '/team-building-monterey',
    conversions: {
      phone: {
        kind: 'send_to',
        accountId: GADS_ID_SECONDARY,
        label: 'a44MCJr2_rYcEKfY2MhD', // "Click to call - Groups LP" in AW-18137623591
        value: 1500,
      },
      form: {
        kind: 'event',
        eventName: 'groups_lp_form_submit',
        value: 1500,
      },
    },
  },
  // Sitewide fallback — phone clicks on the 5 reservations LPs route to the
  // new AW-18137623591 account. Team-building matches first above and is not
  // affected. Lead value $50 (cruiser/kayak floor AOV assumption).
  {
    pathPrefix: '',
    conversions: {
      phone: {
        kind: 'send_to',
        accountId: GADS_ID_SECONDARY,
        label: '0274COCYkbUcEKfY2MhD',
        value: 50,
      },
    },
  },
];

/**
 * Look up the conversion config for a given pathname + type.
 * Returns null if no Google Ads conversion is configured for this combo
 * (caller should still fire any GA4 event, but skip the Ads conversion).
 */
export function getConversionForPath(
  pathname: string,
  type: ConversionType,
): ConversionConfig | null {
  for (const cfg of CONVERSIONS) {
    if (cfg.pathPrefix === '' || pathname.startsWith(cfg.pathPrefix)) {
      const conv = cfg.conversions[type];
      if (conv) return conv;
    }
  }
  return null;
}

declare global {
  interface Window {
    gtag?: (...args: unknown[]) => void;
    fbq?: (...args: unknown[]) => void;
  }
}

export type ConversionOptions = {
  /** The conversion category — routes to the right Google Ads action. */
  type: ConversionType;
  /** If provided, navigation is deferred until the tag fires (or 1-2s elapses). */
  navigateTo?: string;
  /** Optional monetary value override (defaults to the per-page value in CONVERSIONS). */
  value?: number;
  /** Currency override. Defaults to USD. */
  currency?: string;
  /** Optional GA4 event name to fire alongside the Ads conversion (separate event). */
  ga4Event?: string;
  /** Optional GA4 event params. */
  ga4Params?: Record<string, unknown>;
};

/**
 * Fire a Google Ads conversion + optional GA4 event.
 *
 * The conversion config is looked up from CONVERSIONS by the current
 * pathname + type. If no conversion is configured for this pathname + type
 * combo, the GA4 event still fires but the Ads conversion is skipped (and
 * any navigation still happens).
 *
 * For outbound-link clicks (e.g. FareHarbor), pass `navigateTo` AFTER
 * calling e.preventDefault() in the click handler — this helper will
 * navigate for you once the conversion tag has fired (1-2s failsafe).
 */
export function trackConversion(opts: ConversionOptions): void {
  const { type, navigateTo, value, currency = 'USD', ga4Event, ga4Params } = opts;

  // SSR / no-gtag fallback: still navigate if asked, otherwise no-op.
  if (typeof window === 'undefined' || typeof window.gtag !== 'function') {
    if (navigateTo) window.location.href = navigateTo;
    return;
  }

  // GA4 reporting event (separate from the Ads conversion).
  if (ga4Event) {
    window.gtag('event', ga4Event, ga4Params ?? {});
  }

  const pathname = window.location.pathname;
  const conv = getConversionForPath(pathname, type);

  let navigated = false;
  const doNavigate = (): void => {
    if (navigated || !navigateTo) return;
    navigated = true;
    window.location.href = navigateTo;
  };

  // No Ads conversion configured for this page+type — still honor navigation.
  if (!conv) {
    if (navigateTo) {
      // Small delay so any GA4 beacon flushes before navigation.
      window.setTimeout(doNavigate, 100);
    }
    return;
  }

  if (conv.kind === 'send_to') {
    // Legacy style — fire 'conversion' event with send_to.
    const params: Record<string, unknown> = {
      send_to: `${conv.accountId ?? GADS_ID}/${conv.label}`,
      value: typeof value === 'number' ? value : conv.value,
      currency: conv.currency ?? currency,
    };
    if (navigateTo) {
      params.event_callback = doNavigate;
      window.setTimeout(doNavigate, 1000);
    }
    window.gtag('event', 'conversion', params);
  } else {
    // New style — fire custom event by name; Google tag matches it to the
    // Google Ads conversion action configured to trigger on this event.
    const params: Record<string, unknown> = {};
    const effectiveValue = typeof value === 'number' ? value : conv.value;
    if (typeof effectiveValue === 'number') {
      params.value = effectiveValue;
      params.currency = conv.currency ?? currency;
    }
    if (navigateTo) {
      params.event_callback = doNavigate;
      params.event_timeout = 2000;
      window.setTimeout(doNavigate, 2000);
    }
    window.gtag('event', conv.eventName, params);
  }
}
